# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20160825_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='title',
        ),
    ]
