# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_survey_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='multiselect',
            field=models.BooleanField(default=False, verbose_name='Multiselect'),
        ),
    ]
