# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_multiselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='chat_id',
            field=models.TextField(default=None, null=True, verbose_name='Chat_ID'),
        ),
        migrations.AddField(
            model_name='survey',
            name='msg_id',
            field=models.TextField(default=None, null=True, verbose_name='Message_ID'),
        ),
    ]
