# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_create_event_model_in_events_instead_of_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attending', to=settings.AUTH_USER_MODEL),
        ),
    ]
