# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_create_event_model_in_events_instead_of_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='job_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
