# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_attendees'),
        ('events', '0002_event_job_id'),
    ]

    operations = [
    ]
