# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160806_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
    ]
