# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(verbose_name='JSON')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                              serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='Telegram ID')),
            ],
        ),
    ]
