# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramuser_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='picture',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='avatar_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Avatar File ID'),
        ),
    ]
