# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20160608_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='avatar_version',
            field=models.IntegerField(default=0, verbose_name='Avatar Version'),
        ),
    ]
