# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_telegramuser_avatar_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='timezone_offset',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Timezone Offset'),
        ),
    ]
