# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_telegramuser_timezone_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='timezone_setting',
            field=models.CharField(default='Auto', max_length=50, verbose_name='TZ Setting'),
        ),
    ]
