# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_telegramuser_timezone_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='timezone_offset',
        ),
    ]
