# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_telegramuser_timezone_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='timezone_offset',
            field=models.IntegerField(default=0, verbose_name='Timezone Offset'),
        ),
    ]
