# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_telegramuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='timezone_setting',
            field=models.CharField(default='UTC', max_length=50, verbose_name='TZ Setting'),
        ),
    ]
