# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 22:48
from __future__ import unicode_literals

from django.db import migrations


def remove_auto(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("bot", "telegramuser")
    for user in User.objects.all():
        if user.timezone_setting == 'Auto':
            user.timezone_setting = 'UTC'
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20160828_2243'),
    ]

    operations = [
        migrations.RunPython(remove_auto),
    ]
