# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('bot', '0011_auto_20160828_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.CharField(blank=True, max_length=1000, verbose_name='Feedback Text')),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
            ],
        ),
    ]
