# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='telegram_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
    ]
