# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('home', '0002_group_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                              serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='Telegram ID')),
            ],
        ),
    ]
