# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_telegramuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='other_file',
            field=models.FileField(default=None, upload_to='files', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='audios', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to='photos', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='photos_thumb', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='videos_thumb', verbose_name='Thumbnail'),
        ),
    ]
