# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160523_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
