# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160524_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='video',
            name='resolution',
        ),
        migrations.AddField(
            model_name='audio',
            name='album',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Album'),
        ),
        migrations.AddField(
            model_name='audio',
            name='interpret',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Interpret'),
        ),
        migrations.AddField(
            model_name='audio',
            name='type',
            field=models.CharField(default='audio', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(default='link', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='photo',
            name='type',
            field=models.CharField(default='photo', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.CharField(default='text', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(default='video', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='file',
            name='other_file',
            field=models.FileField(upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='group',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='link',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='text',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
    ]
