# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20160527_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('emoji', models.TextField(verbose_name='Emoji')),
                ('file', models.ImageField(upload_to='', verbose_name='File')),
                ('type', models.CharField(default='sticker', max_length=10, verbose_name='Type')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stickers',
                'verbose_name': 'Sticker',
            },
        ),
        migrations.DeleteModel(
            name='TelegramLogEntry',
        ),
    ]
