# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160529_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='emoji',
        ),
    ]
