# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_sticker_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='file',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='link',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='photo',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='text',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='video',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='Telegram ID'),
        ),
    ]
