# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160529_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='album',
        ),
        migrations.AddField(
            model_name='audio',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
    ]
