# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160530_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('allday', models.NullBooleanField(verbose_name='Allday')),
                ('start', models.TimeField(verbose_name='Start')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Group')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
