# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='', max_length=100, verbose_name='Filename'),
            preserve_default=False,
        ),
    ]
