# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_file_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
