# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_album_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='users',
        ),
        migrations.AddField(
            model_name='album',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Group'),
            preserve_default=False,
        ),
    ]
