# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_add_existing_albums_to_group_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='link',
            name='image_url',
            field=models.URLField(default=None, null=True, verbose_name='Image Url'),
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
