# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20160605_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='photo',
            name='media_id',
            field=models.CharField(default='', max_length=100, verbose_name='Media ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='media_mime_type',
            field=models.CharField(default='', max_length=30, verbose_name='Media Mime Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_id',
            field=models.CharField(default='', max_length=100, verbose_name='Thumbnail ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_mime_type',
            field=models.CharField(default='', max_length=30, verbose_name='Thumbnail Mime Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
