# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20160619_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='image_url',
        ),
        migrations.AddField(
            model_name='link',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='Image Url'),
        ),
    ]
