# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20160619_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='doc_type',
            field=models.CharField(max_length=30, verbose_name='Type'),
        ),
    ]
