# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_switch_from_urlField_to_fileField_for_link_preview'),
        ('home', '0020_auto_20160621_2312'),
    ]

    operations = [
    ]
