# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='group',
        ),
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='album',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
        migrations.AlterField(
            model_name='link',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
