# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_move_album_and_event_model_to_other_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Header Image'),
        ),
    ]
