# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_group_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='header_version',
            field=models.IntegerField(default=0, verbose_name='Header Image Version'),
        ),
    ]
