# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_group_header_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories',
                                            to='home.Group')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='childs', to='home.Group')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Directory'),
        ),
    ]
