# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20160808_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='picture',
        ),
        migrations.AddField(
            model_name='group',
            name='chat_photo_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chat Photo File ID'),
        ),
    ]
