# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20160808_2252'),
        ('home', '0028_auto_20160809_1322'),
    ]

    operations = [
    ]
