# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='everyoneIsAdmin',
            field=models.BooleanField(default=True),
        ),
    ]
