# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_group_everyoneisadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='everyoneIsAdmin',
            new_name='everyone_is_admin',
        ),
    ]
