# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20160920_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Photo Version'),
        ),
    ]
